name: Continuous Deployment

on:
  push:
    tags:
      - "*"

jobs:
  publish-github:
    name: Publish on Github
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          $Env:PATH = "${Env:USERPROFILE}\go\bin;${Env:PATH}"
          $version = ${Env:GITHUB_REF}.Replace("refs/tags/","")
          $Env:GO_BUILD_OPTS = "-ldflags `"-w -s -X github.com/yuk7/wsldl/version.version=${version}`""
          $Env:PATH = "${Env:USERPROFILE}\go\bin;${Env:PATH}" 

          echo AMD64 build
          .\build.bat all
          move out out_amd64

          echo ARM64 build
          $Env:GOARCH="arm64"
          .\build.bat all
          move out out_arm64
      - name: Create sha256sums, zip icons and rename
        run: |      
          mkdir out
          echo "creating amd64 artifacts"
          move .\out_amd64\wsldl.exe .\out\wsldl.exe
          Get-ChildItem .\out_amd64\icons -File | Get-FileHash -Algorithm SHA256 | ForEach-Object { $_.hash.toLower() + "  " + ($_.path | Split-Path -Leaf) } | Tee-Object -FilePath .\out_amd64\icons\sha256sums.txt
          Compress-Archive -Path .\out_amd64\icons\* -DestinationPath .\out\icons.zip
          echo "creating arm64 artifacts"
          move .\out_arm64\wsldl.exe .\out\wsldl_arm64.exe
          Get-ChildItem .\out_arm64\icons -File | Get-FileHash -Algorithm SHA256 | ForEach-Object { $_.hash.toLower() + "  " + ($_.path | Split-Path -Leaf) } | Tee-Object -FilePath .\out_arm64\icons\sha256sums.txt
          Compress-Archive -Path .\out_arm64\icons\* -DestinationPath .\out\icons_arm64.zip
          echo "creating all sha256sums"
          Get-ChildItem .\out -File | Get-FileHash -Algorithm SHA256 | ForEach-Object { $_.hash.toLower() + "  " + ($_.path | Split-Path -Leaf) } | Tee-Object -FilePath .\out\sha256sums.txt
      - name: Release body
        run: |
          $version = ${Env:GITHUB_REF}.Replace("refs/tags/","")
          echo "![downloads](https://img.shields.io/github/downloads/yuk7/wsldl/${version}/total?style=flat-square)" > body.txt
      - name: Upload the release
        uses: softprops/action-gh-release@v1
        with:
          body_path: body.txt
          files: |
            out/wsldl.exe
            out/icons.zip
            out/wsldl_arm64.exe
            out/icons_arm64.zip
            out/sha256sums.txt
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
