name: Continuous Deployment

on:
  push:
    tags:
      - '*'
  
jobs:
  publish-github:
    name: Publish on Github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
          export PATH=$PATH:~/go/bin
          cd src
          goversioninfo
          env GOOS=windows GOARCH=amd64 go build -ldflags "-X github.com/yuk7/wsldl/version.version=${VERSION}"
          touch distro.txt
          for f in ../res/*;do
            if [ -d "$f" ]; then
              echo $f >> distro.txt
            fi
          done
          cat distro.txt | while read line;do
            distro="$(echo ${line} | cut -f 3 -d'/')"
            goversioninfo -icon ${line}/icon.ico -o ${distro}.syso
            env GOOS=windows GOARCH=amd64 go build -o ${distro}.exe -ldflags "-X github.com/yuk7/wsldl/version.version=${VERSION}"
            rm -rf ${distro}.syso
          done
      - name: move wsldl to ../
        run: mv src/wsldl.exe wsldl.exe
      - name: Zip package
        run: cd src;7z a icons.zip *.exe;mv icons.zip ../icons.zip
      - name: Release body
        run: echo "![downloads](https://img.shields.io/github/downloads/yuk7/wsldl/${GITHUB_REF}/total?style=flat-square)" > body.txt
      - name: Upload the release
        uses: softprops/action-gh-release@v1
        with:
          body_path: body.txt 
          files: |
            wsldl.exe
            icons.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
